title:       'Die Odyssee'
text_title:  'D&D AUX'
email:       dnd@cle.ar.it
baseurl:     "" # the subpath of your site, e.g. /blog
url:         "https://dndaux.de"
author:      heinlef / ichaelus / kraatob / wayneoween

twitter_username: Wayneoween
github_username: Wayneoween

permalink:     /:title/
paginate:      50
paginate_path: "/posts/page:num/"
excerpt_separator: '<!-- more -->'

# Build settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-coffeescript
  - jekyll-feed

collections:
  characters:
    output: true
  glossary:
    output: false
  quests:
    output: false
